- .env.example
- .gitignore
- src/App.tsx
- src/components/Button/Button.tsx
- src/components/ConnectButton/ConnectButton.tsx
- src/components/Header/Header.module.scss
- src/components/Header/Header.tsx
- src/components/WalletProviderModal/WalletProviderModal.module.scss
- src/components/WalletProviderModal/WalletProviderModal.tsx
- src/index.css
- src/index.tsx
> Connect to Web3 wallet

- src/App.module.scss
- src/App.tsx
- src/components/Footer/Footer.module.scss
- src/components/Footer/Footer.tsx
- src/components/Footer/index.ts
- src/index.module.scss
- src/index.tsx
- src/styles/_variables.scss
- Added common styles like background and text color
- Created Footer component
- Created basic layout for header, content and footer.
> feat: common styles and layout

- src/components/Box/Box.module.scss
- src/components/Box/Box.tsx
- src/components/Box/index.ts
- src/pages/Fundraising/Fundraising.tsx
> feat: Box component

- package-lock.json
- package.json
- src/components/Button/Button.module.scss
- src/components/Button/Button.tsx
- src/pages/Fundraising/Fundraising.tsx
- src/styles/_variables.scss
Added styles to `Button` component.
Created 2 "variants" >> `primary` and `secondary`. Being `primary` the default one.
> feat: Button component

- package-lock.json
- package.json
- src/components/Box/Box.module.scss
- src/components/Button/Button.module.scss
- src/components/CloseButton/CloseButton.module.scss
- src/components/CloseButton/CloseButton.tsx
- src/components/Input/Input.module.scss
- src/components/Layout/Layout.module.scss
- src/components/Layout/Layout.tsx
- src/components/Layout/index.ts
- src/components/Modal/Modal.tsx
- src/components/Title/Title.module.scss
- src/components/Title/Title.tsx
- src/components/Title/index.ts
- src/components/TxStateModals/PendingTx.tsx
- src/components/TxStateModals/RequestedTx.tsx
- src/components/TxStateModals/RevertedTx.tsx
- src/components/TxStateModals/SuccessTx.tsx
- src/components/TxStateModals/TxHash.tsx
- src/components/TxStateModals/TxStateModals.module.scss
- src/components/TxStateModals/UserDeniedTx.tsx
- src/hooks/useWaitTx.tsx
- src/pages/Fundraising/Fundraising.module.scss
- src/pages/Fundraising/Fundraising.tsx
- src/pages/Staking/Staking.module.scss
- src/utils/explorer.ts
Added some user-friendly messages as well as tx hash with a link to the explorer.
Used `react-icons` to add two icons: modal close (cross) icon and external link icon.
Should add some nice illustrations/animations for each state in the near future.
> Tx state modal styling

- src/App.tsx
- src/components/Footer/Footer.module.scss
- src/components/Footer/Footer.tsx
- src/components/Text/Text.module.scss
> Footer social links

- package-lock.json
- package.json
- src/components/WalletProviderModal/WalletProviderModal.tsx
- src/index.tsx
- src/utils/WagmiProvider.tsx
I tested and enabled WalletConnect connector
> WalletConnect

- src/components/Header/Header.module.scss
- src/components/Header/Header.tsx
- src/components/StakingPosition/StakingPosition.module.scss
- src/components/StakingPosition/StakingPosition.tsx
- src/components/StakingPositionsList/StakingPositionsList.module.scss
- src/components/StakingPositionsList/StakingPositionsList.tsx
> Staking position UI

- src/components/Input/Input.tsx
- src/components/ProtocolBalanceInput/ProtocolBalanceInput.module.scss
- src/components/ProtocolBalanceInput/ProtocolBalanceInput.tsx
- src/components/Select/Option.tsx
- src/components/Select/Select.module.scss
- src/components/Select/Select.tsx
- src/components/TokenInput/TokenInput.tsx
- src/hooks/useAmountState.ts
- src/pages/Protocol/Protocol.module.scss
- src/pages/Protocol/Protocol.tsx
> Protocol select component

- src/components/AllowanceGate/AllowanceGate.module.scss
- src/components/AllowanceGate/AllowanceGate.tsx
- src/pages/Fundraising/Fundraising.tsx
- src/pages/Protocol/Protocol.tsx
- src/pages/Staking/Staking.tsx
> Explain two transactions are needed

- src/components/StakingPositionsList/StakingPositionsList.tsx
> Empty positions list message

- src/pages/Fundraising/Fundraising.module.scss
- src/pages/Fundraising/Fundraising.tsx
Don't know if it's the best position, but it is subtle yet visible. 
Suggestions are welcome!
> V1 pool link

- src/App.tsx
once `SHER_BUY_ENTRY_DEADLINE` timestamp is reached:
> feat: update routes post fundraise

- src/components/Input/Input.tsx
- src/components/TokenInput/TokenInput.module.scss
- src/components/TokenInput/TokenInput.tsx
- src/config/mainnet.ts
- src/pages/Staking/Staking.tsx
- Staking USDC APY fixed to 15% (hardcoded).
- Removed staking period selection. Fixed at 6 months.
- Disable staking once TVL of 10M is reached.
> feat: march 30th event

- src/components/StakingPositionsList/StakingPositionsList.tsx
- src/hooks/api/useStakingPositions.tsx
sherlock-protocol/sherlock-v2-indexer#11
> Use individual position USDC APY

- src/hooks/api/axios.ts
> API timeout

- src/components/Loading/Loading.tsx
- src/components/LoadingContainer/LoadingContainer.module.scss
- src/components/LoadingContainer/LoadingContainer.tsx
- src/components/StakingPosition/StakingPosition.tsx
- src/components/StakingPositionsList/StakingPositionsList.module.scss
- src/components/StakingPositionsList/StakingPositionsList.tsx
- src/hooks/api/urls.ts
- src/hooks/api/useWaitForBlock.tsx
- src/pages/Staking/Staking.tsx
> Restaking and unstaking

- src/App.module.scss
- src/App.tsx
- src/components/MobileBlock/MobileBlock.module.scss
- src/components/MobileBlock/MobileBlock.tsx
When accessed via a mobile device, disable the app and show a friendly error message.
> Display error on mobile device

- src/utils/strings.ts
Fix handle regex validation for only ascii characters
> fix: ascii regex

- src/config/mainnet.ts
- src/pages/Staking/Staking.tsx
> Change sherlock claim manager

- src/pages/ContestDetails/ContestDetails.tsx
- src/pages/Contests/ActiveContests.tsx
- src/utils/dates.ts
> feat: display contest time left if < 2 days

- src/components/Markdown/Markdown.tsx
Disable rendering of images from the contest markdown description
> Forbid img tags

- src/hooks/api/contests.ts
- src/pages/ContestDetails/ContestDetails.tsx
- prevent contest from reloading on windows focus.
- do not require Discord for joining a contest.
> fix: contest details

- src/App.tsx
- src/AppContests.tsx
- src/hooks/api/contests.ts
- src/hooks/api/stats/leaderboard/useContestLeaderboard.ts
- src/hooks/api/stats/leaderboard/useLeaderboard.ts
- src/hooks/api/urls.ts
- src/pages/ContestDetails/ContestDetails.tsx
- src/pages/ContestDetails/ContestLeaderboardModal.tsx
- src/pages/Leaderboard/Leaderboard.module.scss
- src/pages/Leaderboard/Leaderboard.tsx
- src/pages/Leaderboard/SeniorWatsonModal.tsx
- src/pages/Leaderboard/index.ts
- src/pages/Scoreboard/index.ts
Linked to https://github.com/sherlock-protocol/contest-api/pull/233
> feat: leaderboard refactor
